Version check for restores

diff --git a/roles/product_install/templates/backup_for_clone.sh.j2 b/roles/product_install/templates/backup_for_clone.sh.j2
--- a/roles/product_install/templates/backup_for_clone.sh.j2
+++ b/roles/product_install/templates/backup_for_clone.sh.j2
@@ -24,16 +24,22 @@ aws_env_vars=$(/usr/local/bin/aws_env_credentials_from_instance_role.sh)
 source $aws_env_vars
 rm $aws_env_vars
 
+current_version=$(basename $(readlink -f /opt/atlassian/*/current))
+echo $current_version | aws s3 cp - "${bucket_url}/VERSION"
+
 #
 # Backup plugin list
 #
 if systemctl is-active --quiet {{ atl_product_family }}; then
-    echo ">>> Backing up plugin list, starting $(date)"
-    plugins_file=$(mktemp)
-    /usr/local/bin/get_upm_plugins.py {{ atl_proxy_name }} > $plugins_file
-    test $? -eq 0 || exit 1
-    aws s3 cp $plugins_file "${bucket_url}/plugins.json"
-    rm $plugins_file
+    if ! test -z $ATL_REST_TOKEN; then
+	echo ">>> Backing up plugin list, starting $(date)"
+	plugins_file=$(mktemp)
+	/usr/local/bin/get_upm_plugins.py {{ atl_proxy_name }} > $plugins_file
+	test $? -eq 0 || exit 1
+	aws s3 cp $plugins_file "${bucket_url}/plugins.json"
+	rm $plugins_file
+    else
+	echo ">>> Can't back up plugins because ATL_REST_TOKEN env var is not set; continuing anyway"
 else
     echo ">>> Can't back up plugins because service isn't running so no access to REST API; continuing anyway"
 fi
diff --git a/roles/product_install/templates/restore_for_clone.sh.j2 b/roles/product_install/templates/restore_for_clone.sh.j2
--- a/roles/product_install/templates/restore_for_clone.sh.j2
+++ b/roles/product_install/templates/restore_for_clone.sh.j2
@@ -8,7 +8,8 @@ if test -z "$s3_backup_url_raw"; then
 Usage: $0 s3_backup_url
 
 Restore cloned database and home directory for app "$APP";
-s3_backup_url must contain files
+s3_backup_url should contain files
+- VERSION       Version of app
 - home.zst      App home tar archive
 - plugins.json  App plugin information
 - database/     Backup as created by mysqlsh
@@ -43,6 +44,17 @@ fi
 
 if ! aws s3 ls "${s3_backup_url}/plugins.json" > /dev/null 2>&1; then
     echo "s3_backup_url doesn't have plugins list; continuing anyway"
+fi
+
+backup_version=$(aws s3 cp "${s3_backup_url}/VERSION" -)
+if test -z $backup_version; then
+    echo "s3_backup_url doesn't have VERSION file; continuing anyway"
+else
+    current_version=$(basename $(readlink -f /opt/atlassian/*/current))
+    if [ "$backup_version" != "$current_version" ]; then
+	echo "Current app version is \"$current_version\", backup version is \"$backup_version\"; can't clone"
+	exit 1
+    fi
 fi
 
 mkdir -p /var/atlassian/application-data/tmp > /dev/null 2>&1
diff --git a/roles/product_install/templates/restore_site.sh.j2 b/roles/product_install/templates/restore_site.sh.j2
--- a/roles/product_install/templates/restore_site.sh.j2
+++ b/roles/product_install/templates/restore_site.sh.j2
@@ -1,16 +1,5 @@
 #!/bin/bash
 
-#
-# FIXME ASSUME S3 URL LOOKS LIKE THIS:
-#
-# base_dir
-#       - home
-#       - database
-#
-# It's faster to sync an uncompressed home directory
-# database directory should be as created by mysqlsh
-#
-
 APP="{{ atl_product_family }}"
 
 s3_backup_url_raw=$1
@@ -19,9 +8,11 @@ if test -z "$s3_backup_url_raw"; then
 Usage: $0 s3_backup_url
 
 Restore database and home directory for app "$APP".
-s3_backup_url must contain files
+s3_backup_url should contain files
+- VERSION       Version of app
 - home.zst      App home tar archive
-- database/   Backup as created by mysqlsh
+- plugins.json  App plugin information
+- database/     Backup as created by mysqlsh
 
 THE APPLICATION MUST BE STOPPED BEFORE RESTORE!
 EOF
@@ -44,6 +35,17 @@ fi
 if ! aws s3 ls "${s3_backup_url}/database" > /dev/null 2>&1; then
     echo "s3_backup_url doesn't have database"
     exit 1
+fi
+
+backup_version=$(aws s3 cp "${s3_backup_url}/VERSION" -)
+if test -z $backup_version; then
+    echo "s3_backup_url doesn't have VERSION file; continuing anyway"
+else
+    current_version=$(basename $(readlink -f /opt/atlassian/*/current))
+    if [ "$backup_version" != "$current_version" ]; then
+	echo "Current app version is \"$current_version\", backup version is \"$backup_version\"; can't clone"
+	exit 1
+    fi
 fi
 
 # /var/tmp is bigger
